### ISSUE TITLE
Fails to compile with GHC 7.0.4, GHC 7.2.2, and GHC 7.4.2

### ISSUE THREAD

**Issue by hvr** [GaloisInc/RSA#10]
This is due to the use of `MultiWayIf` which is only available starting with GHC 7.6:

```
Configuring RSA-2.1.0...
cabal: The package RSA-2.1.0 requires the following language extensions which
are not supported by ghc-7.4.2: MultiWayIf
Failed to install RSA-2.1.0
cabal: Error: some packages failed to install:
RSA-2.1.0 failed during the configure step. The exception was:
ExitFailure 1
```

Please add a `base >= 4.6` constraint to future releases (or make RSA compatible with GHC < 7.6 again)

See also https://ghc.haskell.org/~hvr/buildreports/RSA.html

**Comment by acw** [comment]
This should be fixed in version 2.1.0.1 / 0d9763b. As soon as it clears our build / test system I'll upload the new version to Hackage.
